#!/usr/bin/env python3
"""Write the Luau layout module PrebuiltMaps reads, from a split's layout.json.

    python3 tools/city_import/emit_layout.py assets/maps/<map>/layout.json [--check]
    python3 tools/city_import/emit_layout.py --all [--check]

The module is src/shared/prebuilt/<map>.luau: per cell its name, position, size,
triangle and texture counts and meshes (name, offset, size, triangles, collision).
Asset ids are not in it; PrebuiltMaps reads them from AssetIds.model.maps.<map>.<cell>,
so ids keep flowing through the manifest pipeline. --all covers every
assets/maps/*/layout.json; --check exits non-zero when a module is out of date.
"""

import argparse
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))


def _number(value):
    value = round(float(value), 4)
    if value == 0:
        return "0"
    return str(int(value)) if value.is_integer() else repr(value)


def _vector(values):
    return "{ " + ", ".join(_number(v) for v in values) + " }"


def _string(text):
    return '"' + str(text).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(map_name, layout):
    out = [
        "--!strict",
        "",
        f"-- Generated by tools/city_import/emit_layout.py from assets/maps/{map_name}/layout.json.",
        "-- Do not edit by hand. Read by PrebuiltMaps (docs/environment/prebuilt-maps.md); the",
        f"-- cells' asset ids come from AssetIds.model.maps.{map_name}.",
        "",
        "return {",
        f"\tmap = {_string(map_name)},",
        f"\tsource = {_string(layout.get('source', ''))},",
        f"\tscale = {_number(layout['scale'])},",
        f"\tcellSize = {_number(layout['cell'])},",
        f"\tmaxTris = {int(layout['maxTris'])},",
        "\tcells = {",
    ]
    for cell in layout["cells"]:
        out.append("\t\t{")
        out.append(f"\t\t\tname = {_string(cell['name'])},")
        out.append(f"\t\t\tposition = {_vector(cell['position'])},")
        out.append(f"\t\t\tsize = {_vector(cell['size'])},")
        out.append(f"\t\t\ttriangles = {int(cell['triangles'])},")
        out.append(f"\t\t\ttextures = {int(cell['textures'])},")
        out.append("\t\t\tmeshes = {")
        for mesh in cell["meshes"]:
            out.append(
                f"\t\t\t\t{{ name = {_string(mesh['name'])}, offset = {_vector(mesh['offset'])}, "
                f"size = {_vector(mesh['size'])}, triangles = {int(mesh['triangles'])}, "
                f"collision = {_string(mesh['collision'])} }},"
            )
        out.append("\t\t\t},")
        out.append("\t\t},")
    out.append("\t},")
    out.append("}")
    out.append("")
    return "\n".join(out)


def module_path(map_name, root=REPO):
    return os.path.join(root, "src", "shared", "prebuilt", f"{map_name}.luau")


def write(map_name, layout, root=REPO, check=False):
    path = module_path(map_name, root)
    content = render(map_name, layout)
    existing = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            existing = handle.read()
    if check:
        return existing == content
    if existing != content:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)
    return path


def map_of(layout_path, layout):
    return layout.get("map") or os.path.basename(os.path.dirname(os.path.abspath(layout_path)))


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("layout", nargs="?", help="a layout.json")
    parser.add_argument("--all", action="store_true", help="every assets/maps/*/layout.json")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    paths = sorted(glob.glob(os.path.join(REPO, "assets", "maps", "*", "layout.json"))) if args.all else [args.layout]
    if not paths or paths == [None]:
        if args.all:
            print("no prebuilt map layouts")
            return 0
        parser.error("give a layout.json or --all")
    stale = []
    for path in paths:
        with open(path, encoding="utf-8") as handle:
            layout = json.load(handle)
        name = map_of(path, layout)
        if args.check:
            if not write(name, layout, check=True):
                stale.append(name)
        else:
            print(f"wrote {os.path.relpath(write(name, layout), REPO)}")
    if stale:
        print(f"out of date: {', '.join(stale)}; run tools/city_import/emit_layout.py --all")
        return 1
    if args.check:
        print("prebuilt map layouts up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
