#!/usr/bin/env python3
"""Pack clips baked by gltf_anim.py into a Luau ModuleScript for ViewmodelClipPlayer.

    python3 emit_luau.py baked.json out.luau --scale 3.2 [--rename Old=New ...] [--skip REGEX]

--scale   studs per file unit (glTF metres); applied to translations only
--rename  rename a clip (the pack's names become our sequence names)
--skip    joints to drop (regex on the joint name), e.g. fingers that never matter

Encoding per track (one base64 string): u16 key count, then per key u16 frame index
and 7 x i16: x, y, z in 1/2000 stud, qx, qy, qz, qw in 1/32767. Keys that linear
interpolation between their neighbours reproduces within tolerance are dropped.
"""

import base64
import json
import re
import struct
import sys

import numpy as np

POS_TOL = 0.002  # studs
ANG_TOL = np.radians(0.25)
POS_Q = 2000.0
ROT_Q = 32767.0


def angle(a, b):
    d = abs(float(np.dot(a, b)))
    return 2 * np.arccos(min(1.0, d))


def nlerp(a, b, u):
    if np.dot(a, b) < 0:
        b = -b
    q = a * (1 - u) + b * u
    return q / np.linalg.norm(q)


def reduce_keys(rows):
    rows = np.asarray(rows, float)
    n = len(rows)
    if n <= 2:
        return list(range(n))
    keep = [0]
    anchor = 0
    for i in range(2, n):
        ok = True
        for k in range(anchor + 1, i):
            u = (k - anchor) / (i - anchor)
            p = rows[anchor, :3] * (1 - u) + rows[i, :3] * u
            q = nlerp(rows[anchor, 3:], rows[i, 3:], u)
            if np.linalg.norm(p - rows[k, :3]) > POS_TOL or angle(q, rows[k, 3:]) > ANG_TOL:
                ok = False
                break
        if not ok:
            keep.append(i - 1)
            anchor = i - 1
    keep.append(n - 1)
    return keep


def pack(rows, scale):
    rows = np.asarray(rows, float).copy()
    rows[:, :3] *= scale
    # the baked quaternions are rounded to 5 decimals; unnormalised they differ from
    # themselves by about 0.3 degrees in angle(), which defeats the key reduction
    rows[:, 3:] /= np.linalg.norm(rows[:, 3:], axis=1, keepdims=True)
    if np.abs(rows[:, :3]).max() * POS_Q > 32767:
        raise SystemExit("translation out of i16 range; lower --scale or POS_Q")
    keys = reduce_keys(rows)
    out = bytearray(struct.pack("<H", len(keys)))
    for k in keys:
        r = rows[k]
        vals = [int(round(v * POS_Q)) for v in r[:3]] + [int(round(v * ROT_Q)) for v in r[3:]]
        out += struct.pack("<H7h", k, *vals)
    return base64.b64encode(bytes(out)).decode("ascii"), len(keys)


def main():
    args = sys.argv[1:]
    if len(args) < 2:
        print(__doc__)
        return 1
    src, dst = args[0], args[1]
    scale = float(args[args.index("--scale") + 1]) if "--scale" in args else 1.0
    renames = {}
    skip = None
    for i, a in enumerate(args):
        if a == "--rename":
            old, new = args[i + 1].split("=", 1)
            renames[old] = new
        if a == "--skip":
            skip = re.compile(args[i + 1])
    data = json.load(open(src))
    lines = [
        "--!strict",
        f"-- GENERATED by tools/fps_pack/emit_luau.py from {data['source']}. Do not edit by hand.",
        "-- Tracks are base64 strings decoded by ViewmodelClipPlayer.",
        "",
        "return {",
        f"\tfps = {data['fps']:g},",
    ]
    extras = data.get("extras") or {}
    if extras:
        lines.append("\textras = {")
        for name, row in extras.items():
            vals = [row[0] * scale, row[1] * scale, row[2] * scale, *row[3:]]
            lines.append(f"\t\t[{json.dumps(name)}] = {{ {', '.join(f'{v:.5f}' for v in vals)} }},")
        lines.append("\t},")
    lines.append("\tclips = {")
    total_keys = 0
    for clip in data["clips"]:
        if clip["duration"] <= 0:
            continue
        name = renames.get(clip["name"], clip["name"])
        lines.append(f"\t\t[{json.dumps(name)}] = {{")
        lines.append(f"\t\t\tduration = {clip['duration']:g},")
        lines.append(f"\t\t\tframes = {clip['frames']},")
        lines.append("\t\t\ttracks = {")
        kept = 0
        for joint, rows in clip["tracks"].items():
            if skip and skip.search(joint):
                continue
            blob, n = pack(rows, scale)
            total_keys += n
            kept += 1
            lines.append(f"\t\t\t\t[{json.dumps(joint)}] = \"{blob}\",")
        lines.append("\t\t\t},")
        lines.append("\t\t},")
        print(f"{name}: {kept} joints")
    lines += ["\t},", "}", ""]
    open(dst, "w").write("\n".join(lines))
    size = sum(len(l) for l in lines)
    print(f"wrote {dst}: {total_keys} keys, {size / 1024:.0f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
