"""Build the mesh template and rig config for a split R15 zombie.

Inputs:
  assets/zombies/<name>/rig.json            part centres/sizes/textures and joint pivots
                                            (written by tools/zombie_rig/split_rig.py)
  manifest rows zombie/<name>/meshid/<part> mesh ids read back in Studio after the
                                            zombie/<name>/mesh/<part> Model uploads

Outputs:
  assets/zombies/<name>.model.json          MeshPart templates, mounted by default.project.json
                                            under ReplicatedStorage.ZombieMeshes.<Name>
  src/shared/config/ZombieRigConfig.luau    joints and part placement for ZombieFactory

Everything is written at scale 1 in character space (feet at y = 0, facing -Z);
ZombieFactory applies its SCALE at build time.

    python3 scripts/build_zombie_rig.py walker2
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "assets", "manifest.json")


def fmt(v):
    return f"{v:.4f}".rstrip("0").rstrip(".") if v != int(v) else f"{int(v)}"


def main(name):
    with open(os.path.join(ROOT, "assets", "zombies", name, "rig.json")) as handle:
        rig = json.load(handle)
    with open(MANIFEST) as handle:
        manifest = json.load(handle)

    children, missing = [], []
    for part, info in rig["parts"].items():
        entry = manifest.get(f"zombie/{name}/meshid/{part.lower()}") or {}
        try:
            mesh = int(entry.get("assetId") or 0)
        except (TypeError, ValueError):
            mesh = 0
        if mesh <= 0:
            missing.append(part)
        children.append({
            "className": "MeshPart",
            "name": part,
            "properties": {
                "Size": info["size"],
                "Anchored": True,
                "CanCollide": False,
                "CanQuery": False,
                "CanTouch": False,
                "MeshId": f"rbxassetid://{mesh}",
                "TextureID": f"rbxassetid://{info['texture']}",
            },
        })
    out = os.path.join(ROOT, "assets", "zombies", name + ".model.json")
    with open(out, "w") as handle:
        json.dump({"className": "Model", "children": children}, handle, indent=2)
        handle.write("\n")

    lines = [
        "--!strict",
        "",
        "-- GENERATED by scripts/build_zombie_rig.py from assets/zombies/<rig>/rig.json.",
        "-- Do not edit by hand: re-run the script after re-splitting a zombie.",
        "--",
        "-- Character space at scale 1: feet at y = 0, facing -Z. `centre` is where each",
        "-- MeshPart template sits, `pivot` is the joint position; C0/C1 are the pivot",
        "-- minus the part centres, with no rotation (all joint frames are axis-aligned,",
        "-- like Roblox's own R15 rig, so stock R15 clips play unchanged).",
        "",
        "export type Joint = { name: string, part0: string, part1: string, pivot: Vector3 }",
        "export type Rig = {",
        "\trootY: number,",
        "\tparts: { [string]: { centre: Vector3, size: Vector3 } },",
        "\tjoints: { Joint },",
        "}",
        "",
        "local ZombieRigConfig: { [string]: Rig } = {}",
        "",
        f"ZombieRigConfig.{name} = {{",
        f"\trootY = {fmt(rig['rootY'])},",
        "\tparts = {",
    ]
    for part, info in rig["parts"].items():
        c, s = info["center"], info["size"]
        lines.append(f"\t\t{part} = {{ centre = Vector3.new({', '.join(fmt(x) for x in c)}), size = Vector3.new({', '.join(fmt(x) for x in s)}) }},")
    lines.append("\t},")
    lines.append("\tjoints = {")
    for j in rig["joints"]:
        p = j["pivot"]
        lines.append(f"\t\t{{ name = \"{j['name']}\", part0 = \"{j['part0']}\", part1 = \"{j['part1']}\", pivot = Vector3.new({', '.join(fmt(x) for x in p)}) }},")
    lines += ["\t},", "}", "", "return ZombieRigConfig", ""]
    with open(os.path.join(ROOT, "src", "shared", "config", "ZombieRigConfig.luau"), "w") as handle:
        handle.write("\n".join(lines))
    print("wrote", os.path.relpath(out, ROOT), "and ZombieRigConfig.luau; missing mesh ids:", missing or "none")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "walker2"))
