#!/usr/bin/env python3
"""Build the first-person arm templates and their rig config.

Inputs:
  assets/viewmodels/arms/rig.json            part centres/sizes, wrist frame per side
                                             (written by tools/arms_rig/build.py)
  manifest rows viewmodel/arms/meshid/<part> mesh ids read back in Studio after the
                                             viewmodel/arms/mesh/<part> Model uploads
  manifest rows viewmodel/arms/texture/*     SurfaceAppearance maps (Image uploads)

Outputs:
  assets/viewmodels/arms.model.json          MeshPart templates, mounted by
                                             default.project.json as ReplicatedStorage.ViewModelArms
  src/shared/config/ArmRigConfig.luau        per-side placement for ViewmodelBuilder

Units are studs before ViewmodelConfig.SCALE; ViewmodelBuilder applies the scale.

    python3 scripts/build_arms.py
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "assets", "manifest.json")
RIG = os.path.join(ROOT, "assets", "viewmodels", "arms", "rig.json")
MODEL_OUT = os.path.join(ROOT, "assets", "viewmodels", "arms.model.json")
CONFIG_OUT = os.path.join(ROOT, "src", "shared", "config", "ArmRigConfig.luau")


def fmt(v):
    return f"{v:.5f}".rstrip("0").rstrip(".") if v != int(v) else f"{int(v)}"


def asset_id(manifest, key):
    entry = manifest.get(key) or {}
    try:
        return int(entry.get("assetId") or 0)
    except (TypeError, ValueError):
        return 0


def main():
    with open(RIG) as handle:
        rig = json.load(handle)
    with open(MANIFEST) as handle:
        manifest = json.load(handle)

    children, missing = [], []
    for side, entry in rig["sides"].items():
        s = side.lower()
        maps = {
            "ColorMap": asset_id(manifest, f"viewmodel/arms/texture/arm{s}_color"),
            "RoughnessMap": asset_id(manifest, f"viewmodel/arms/texture/arm{s}_roughness"),
        }
        # A SurfaceAppearance whose NormalMap fails to load renders the whole part white
        # (seen 2026-09-28 while the normal maps were still in moderation), so the normal
        # maps are opt-in until they load: python3 scripts/build_arms.py --normals
        if "--normals" in sys.argv:
            maps["NormalMap"] = asset_id(manifest, f"viewmodel/arms/texture/arm{s}_normal")
        for part in ("Hand", "Forearm"):
            mesh = asset_id(manifest, f"viewmodel/arms/meshid/{part.lower()}{s}")
            if mesh <= 0:
                missing.append(part + side)
            node = {
                "className": "MeshPart",
                "name": part + side,
                "properties": {
                    "Size": entry[part]["size"],
                    "Anchored": True,
                    "CanCollide": False,
                    "CanQuery": False,
                    "CanTouch": False,
                    "CastShadow": False,
                    "MeshId": f"rbxassetid://{mesh}",
                },
            }
            surface = {k: f"rbxassetid://{v}" for k, v in maps.items() if v > 0}
            if surface:
                surface["AlphaMode"] = "Overlay"
                node["children"] = [{"className": "SurfaceAppearance", "name": "SurfaceAppearance", "properties": surface}]
            children.append(node)
    with open(MODEL_OUT, "w") as handle:
        json.dump({"className": "Model", "children": children}, handle, indent=2)
        handle.write("\n")

    lines = [
        "--!strict",
        "",
        "-- GENERATED by scripts/build_arms.py from assets/viewmodels/arms/rig.json.",
        "-- Do not edit by hand: re-run tools/arms_rig/build.py and this script instead.",
        "--",
        "-- Hand frame: fingers toward -Z, back of the hand +Y, origin on the grip axis.",
        "-- `handCentre` is where the Hand MeshPart centre sits in that frame. `wrist` is the",
        "-- forearm frame (origin at the wrist, forearm running toward +Z) in the hand frame,",
        "-- and `forearmCentre` the Forearm MeshPart centre in the forearm frame.",
        "-- Studs before ViewmodelConfig.SCALE.",
        "",
        "export type Side = {",
        "\thandCentre: Vector3,",
        "\thandSize: Vector3,",
        "\twrist: CFrame,",
        "\tforearmCentre: Vector3,",
        "\tforearmSize: Vector3,",
        "}",
        "",
        "local ArmRigConfig = {}",
        "",
        f"-- false until every arm MeshId has been read back into the manifest",
        f"ArmRigConfig.ready = {'false' if missing else 'true'}",
        "",
    ]
    for side, entry in rig["sides"].items():
        hc, hs = entry["Hand"]["center"], entry["Hand"]["size"]
        fc, fs = entry["Forearm"]["center"], entry["Forearm"]["size"]
        w, r = entry["wrist"], entry["foreRot"]
        rot = ", ".join(fmt(x) for row in r for x in row)
        lines += [
            f"ArmRigConfig.{side} = {{",
            f"\thandCentre = Vector3.new({', '.join(fmt(x) for x in hc)}),",
            f"\thandSize = Vector3.new({', '.join(fmt(x) for x in hs)}),",
            f"\twrist = CFrame.new({', '.join(fmt(x) for x in w)}, {rot}),",
            f"\tforearmCentre = Vector3.new({', '.join(fmt(x) for x in fc)}),",
            f"\tforearmSize = Vector3.new({', '.join(fmt(x) for x in fs)}),",
            "} :: Side",
            "",
        ]
    lines += ["return ArmRigConfig", ""]
    with open(CONFIG_OUT, "w") as handle:
        handle.write("\n".join(lines))
    print("wrote", os.path.relpath(MODEL_OUT, ROOT), "and ArmRigConfig.luau; missing mesh ids:", missing or "none")


if __name__ == "__main__":
    sys.exit(main())
