"""Build the mesh template and rig config for the third-person soldier body.

Inputs:
  assets/character/soldier/source/rig.json     part centres/sizes, joint pivots, grips
                                               (written by tools/character_rig/soldier.py)
  manifest rows character/soldier/meshid/<part> mesh ids read back in Studio after the
                                               character/soldier/mesh/<part> Model uploads
  manifest rows character/soldier/texture/<group>_<map>  the SurfaceAppearance maps

Outputs:
  assets/character/soldier.model.json          MeshPart templates with SurfaceAppearance,
                                               mounted by default.project.json under
                                               ReplicatedStorage.CharacterMeshes.Soldier
  src/shared/config/SoldierRigConfig.luau      joints, part placement, hip height, grips
                                               and `ready` (every mesh id is filled in)

    python3 scripts/build_soldier_rig.py
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "assets", "manifest.json")
RIG = os.path.join(ROOT, "assets", "character", "soldier", "source", "rig.json")
MAPS = ("Color", "Normal", "Roughness")


def fmt(v):
    return f"{v:.4f}".rstrip("0").rstrip(".") if v != int(v) else f"{int(v)}"


def vec(values):
    return f"Vector3.new({', '.join(fmt(x) for x in values)})"


def asset(manifest, key):
    try:
        return int((manifest.get(key) or {}).get("assetId") or 0)
    except (TypeError, ValueError):
        return 0


def main():
    with open(RIG) as handle:
        rig = json.load(handle)
    with open(MANIFEST) as handle:
        manifest = json.load(handle)

    children, missing = [], []
    for part, info in rig["parts"].items():
        if part == "HumanoidRootPart":
            continue
        mesh = asset(manifest, f"character/soldier/meshid/{part.lower()}")
        if mesh <= 0:
            missing.append(part)
        appearance = {"AlphaMode": "Overlay"}
        for kind in MAPS:
            image = asset(manifest, f"character/soldier/texture/{info['group'].lower()}_{kind.lower()}")
            if image > 0:
                appearance[f"{kind}Map"] = f"rbxassetid://{image}"
        children.append({
            "className": "MeshPart",
            "name": part,
            "properties": {
                "Size": info["size"],
                "Anchored": True,
                "CanCollide": False,
                "CanQuery": False,
                "CanTouch": False,
                "MeshId": f"rbxassetid://{mesh}",
            },
            "children": [{"className": "SurfaceAppearance", "name": "SurfaceAppearance", "properties": appearance}],
        })
    out = os.path.join(ROOT, "assets", "character", "soldier.model.json")
    with open(out, "w") as handle:
        json.dump({"className": "Model", "children": children}, handle, indent=2)
        handle.write("\n")

    lines = [
        "--!strict",
        "",
        "-- GENERATED by scripts/build_soldier_rig.py from assets/character/soldier/source/rig.json.",
        "-- Do not edit by hand: re-run tools/character_rig/soldier.py and the script instead.",
        "--",
        "-- Character space: feet at y = 0, facing -Z. `centre` is where each MeshPart sits in",
        "-- the rest pose (arms hanging straight down, like Roblox's own R15), `pivot` is the",
        "-- joint position; every joint frame is axis-aligned so stock R15 clips play",
        "-- unchanged. `grips` is each fist's centre relative to its hand part, where a weapon",
        "-- grip sits. `ready` is false until every part has a mesh id.",
        "",
        "export type Joint = { name: string, part0: string, part1: string, pivot: Vector3 }",
        "export type Part = { centre: Vector3, size: Vector3, group: string? }",
        "",
        "local SoldierRigConfig = {}",
        "",
        f"SoldierRigConfig.ready = {'true' if not missing else 'false'}",
        f"SoldierRigConfig.hipHeight = {fmt(rig['hipHeight'])}",
        f"SoldierRigConfig.height = {fmt(rig['height'])}",
        "",
        "SoldierRigConfig.parts = {",
    ]
    for part, info in rig["parts"].items():
        group = f"\"{info['group']}\"" if info["group"] else "nil"
        lines.append(f"\t{part} = {{ centre = {vec(info['centre'])}, size = {vec(info['size'])}, group = {group} }},")
    lines += ["} :: { [string]: Part }", "", "SoldierRigConfig.joints = {"]
    for j in rig["joints"]:
        lines.append(f"\t{{ name = \"{j['name']}\", part0 = \"{j['part0']}\", part1 = \"{j['part1']}\", pivot = {vec(j['pivot'])} }},")
    lines += ["} :: { Joint }", "", "SoldierRigConfig.grips = {"]
    for side, offset in rig["grips"].items():
        lines.append(f"\t{side} = {vec(offset)},")
    lines += ["}", "", "return SoldierRigConfig", ""]
    with open(os.path.join(ROOT, "src", "shared", "config", "SoldierRigConfig.luau"), "w") as handle:
        handle.write("\n".join(lines))
    print("wrote", os.path.relpath(out, ROOT), "and SoldierRigConfig.luau; missing mesh ids:", missing or "none")


if __name__ == "__main__":
    sys.exit(main())
