#!/usr/bin/env python3
"""Regenerate assets/NEEDED.md — the shopping list of empty asset slots.

An empty slot is any manifest entry whose assetId is 0 or missing. Rejected
uploads count as empty too: the id exists but must not be used.

Usage:
    python3 scripts/sync_needed.py
    python3 scripts/sync_needed.py --check   # non-zero exit if the file is stale
"""

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "assets", "manifest.json")
OUTPUT = os.path.join(ROOT, "assets", "NEEDED.md")

# Per-slot guidance: where the slot is consumed, what to search for, priority.
GUIDE = {
    "animation/player/run": ("AnimationController — run cycle", "Mixamo: Running (in place, rifle carry)", "blocker"),
    "animation/player/strafe_left": ("AnimationController — lateral dodge", "Mixamo: Left Strafe (in place)", "blocker"),
    "animation/player/strafe_right": ("AnimationController — lateral dodge", "Mixamo: Right Strafe (in place)", "blocker"),
    "animation/player/stumble": ("AnimationController — obstacle clip", "Mixamo: Stumble Backwards", "polish"),
    "animation/player/death": ("DeathService / DeathController — supine death pose", "Mixamo: Falling Back Death", "blocker"),
    "animation/zombie/idle_a": ("ZombieAnimator — idle variation", "Mixamo: Zombie Idle", "blocker"),
    "animation/zombie/idle_b": ("ZombieAnimator — idle variation", "Mixamo: Zombie Neck Bite (idle part)", "polish"),
    "animation/zombie/idle_c": ("ZombieAnimator — rise from ground", "Mixamo: Zombie Stand Up", "polish"),
    "animation/zombie/walk_shuffle": ("ZombieAnimator — walker gait", "Mixamo: Zombie Walk (in place)", "blocker"),
    "animation/zombie/run_ragged": ("ZombieAnimator — runner gait", "Mixamo: Zombie Running (in place)", "blocker"),
    "animation/zombie/attack_lunge": ("ZombieAI — touch attack", "Mixamo: Zombie Attack", "blocker"),
    "animation/zombie/feeding": ("DeathService — corpse feeding loop", "Mixamo: Zombie Feeding", "blocker"),
    "animation/weapon/fire": ("Viewmodel — clip layer over spring recoil", "Universal Viewmodel Template: fire", "polish"),
    "animation/weapon/reload": ("Viewmodel — replaces procedural reload", "Universal Viewmodel Template: reload", "polish"),
    "animation/weapon/equip": ("Viewmodel — replaces procedural raise", "Universal Viewmodel Template: raise/equip", "polish"),
    "animation/weapon/inspect": ("Viewmodel — F key inspect", "Universal Viewmodel Template: inspect", "polish"),
    "animation/weapon/sprint": ("Viewmodel — sprint carry pose", "Universal Viewmodel Template: sprint/run", "polish"),
}

CATEGORY_TITLES = {
    "animation": "Animation",
    "audio": "Audio",
    "texture": "Texture",
}


def load_manifest():
    with open(MANIFEST, "r", encoding="utf-8") as handle:
        return json.load(handle)


def empty_slots(manifest):
    slots = []
    for key, entry in sorted(manifest.items()):
        asset_id = str(entry.get("assetId") or "0").strip()
        status = str(entry.get("status") or "pending")
        if asset_id in ("", "0") or status == "rejected":
            slots.append((key, status))
    return slots


def render(slots):
    lines = [
        "# Needed assets",
        "",
        "Generated by `scripts/sync_needed.py` from `assets/manifest.json`. Every row is a slot that is",
        "currently silent or unanimated because no approved asset backs it. Systems guard on `assetId > 0`,",
        "so an empty slot degrades to nothing happening rather than an error.",
        "",
        "Rules for filling these are in [docs/asset-policy.md](../docs/asset-policy.md): real licensed files",
        "only, no synthesis, no invented ids.",
        "",
    ]

    if not slots:
        lines.append("Nothing outstanding — every manifest slot has an approved asset.")
        lines.append("")
        return "\n".join(lines)

    grouped = {}
    for key, status in slots:
        category = key.split("/")[0]
        grouped.setdefault(category, []).append((key, status))

    for category in sorted(grouped):
        lines.append(f"## {CATEGORY_TITLES.get(category, category.title())}")
        lines.append("")
        lines.append("| Slot | Used by | What to look for | Priority | Status |")
        lines.append("| --- | --- | --- | --- | --- |")
        for key, status in grouped[category]:
            used_by, search, priority = GUIDE.get(key, ("—", "—", "polish"))
            lines.append(f"| `{key}` | {used_by} | {search} | {priority} | {status} |")
        lines.append("")

    blockers = [key for key, _ in slots if GUIDE.get(key, ("", "", "polish"))[2] == "blocker"]
    lines.append(f"**{len(blockers)} blockers, {len(slots) - len(blockers)} polish items.**")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit non-zero when the file is out of date")
    args = parser.parse_args()

    manifest = load_manifest()
    content = render(empty_slots(manifest))

    if args.check:
        current = ""
        if os.path.exists(OUTPUT):
            with open(OUTPUT, "r", encoding="utf-8") as handle:
                current = handle.read()
        if current != content:
            print("assets/NEEDED.md is out of date, run scripts/sync_needed.py")
            return 1
        print("assets/NEEDED.md is up to date")
        return 0

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write(content)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
