#!/usr/bin/env python3
"""Generate src/shared/config/AssetIds.luau, assets/LICENSES.md and the prop surface
templates (assets/props/surfaces.model.json) from the manifest.

Manifest keys are slash separated (audio/footsteps/metal_01) and become nested
Luau tables (AssetIds.audio.footsteps.metal_01). Entries without an approved
assetId are emitted as 0 so consumers stay silent instead of erroring.

Usage:
    python3 scripts/sync_configs.py [--check]

--check exits non-zero if the generated files are out of date, for CI use.
"""

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "assets", "manifest.json")
LUAU_OUT = os.path.join(ROOT, "src", "shared", "config", "AssetIds.luau")
LICENSES_OUT = os.path.join(ROOT, "assets", "LICENSES.md")
SURFACES_OUT = os.path.join(ROOT, "assets", "props", "surfaces.model.json")

# texture/props/<prop>_<suffix> -> SurfaceAppearance property
SURFACE_MAPS = (
    ("color", "ColorMap"),
    ("normal", "NormalMap"),
    ("roughness", "RoughnessMap"),
    ("metalness", "MetalnessMap"),
)

HEADER = "--!strict\n\n-- Generated by scripts/sync_configs.py from assets/manifest.json. Do not edit by hand.\n\n"


def load_manifest():
    with open(MANIFEST) as handle:
        return json.load(handle)


def build_tree(manifest):
    tree = {}
    for key, entry in sorted(manifest.items()):
        parts = key.split("/")
        node = tree
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        asset_id = entry.get("assetId") or 0
        if entry.get("status") == "rejected":
            asset_id = 0
        node[parts[-1]] = asset_id
    return tree


def render(node, indent):
    pad = "\t" * indent
    lines = []
    for name in sorted(node.keys()):
        value = node[name]
        if isinstance(value, dict):
            lines.append(f"{pad}{name} = {{")
            lines.extend(render(value, indent + 1))
            lines.append(f"{pad}}},")
        else:
            lines.append(f"{pad}{name} = {value},")
    return lines


def render_luau(manifest):
    tree = build_tree(manifest)
    body = "\n".join(render(tree, 1))
    return f"{HEADER}local AssetIds = {{\n{body}\n}}\n\nreturn table.freeze(AssetIds)\n"


def render_licenses(manifest):
    rows = ["# Asset licenses", "", "Generated by `scripts/sync_configs.py`. Do not edit by hand.", ""]
    rows.append(
        "Anything marked **CC-BY** obliges us to credit the named author in the shipped game, "
        "not only in this file. Those credits belong in the in-game settings panel before "
        "release. CC0 and public-domain entries carry no such obligation. Share-alike "
        "(CC BY-SA) licences are deliberately not used anywhere here, because they would "
        "extend a copyleft obligation over the game itself."
    )
    rows.append("")
    rows.append("| Asset | License | Source | Asset ID | Status |")
    rows.append("| --- | --- | --- | --- | --- |")
    for key, entry in sorted(manifest.items()):
        source = entry.get("source", "")
        source_cell = f"[link]({source})" if source.startswith("http") else source
        rows.append(
            f"| `{key}` | {entry.get('license', '')} | {source_cell} | "
            f"{entry.get('assetId') or '—'} | {entry.get('status', '')} |"
        )
    rows.append("")
    rows.append("Generated audio and textures marked `Original work (project owner)` were synthesised for this project.")
    if any(entry.get("license", "").startswith("Roblox generative AI output") for entry in manifest.values()):
        rows.append("")
        rows.append(
            "Entries marked `Roblox generative AI output (project owner)` are Cube 3D meshes and albedo maps "
            "produced by Roblox's GenerationService inside this project's own place and uploaded under the "
            "project owner's account; Roblox grants the generating creator the rights to use that output."
        )
    rows.append("")
    return "\n".join(rows)


def usable_id(entry):
    if not entry or entry.get("status") == "rejected":
        return 0
    return int(entry.get("assetId") or 0)


def render_surfaces(manifest):
    """One SurfaceAppearance per uploaded prop (model/props/<name>), named after the prop.

    SurfaceAppearance maps cannot be written by a game script, so WorldMeshes clones
    these Rojo-mounted templates (ReplicatedStorage.PropSurfaces) onto the MeshParts it
    creates. A prop entry may set "alphaMode" (for example "Transparency" for cut-out
    road signs); the default is Overlay.
    """
    children = []
    names = sorted(key.split("/", 2)[2] for key in manifest if key.startswith("model/props/"))
    for name in names:
        properties = {}
        for suffix, prop in SURFACE_MAPS:
            asset_id = usable_id(manifest.get(f"texture/props/{name}_{suffix}"))
            if asset_id:
                properties[prop] = f"rbxassetid://{asset_id}"
        if "ColorMap" not in properties:
            continue
        alpha = manifest[f"model/props/{name}"].get("alphaMode")
        if alpha:
            properties["AlphaMode"] = alpha
        children.append({"className": "SurfaceAppearance", "name": name, "properties": properties})
    tree = {"className": "Folder", "children": children}
    return json.dumps(tree, indent=2) + "\n"


def write_if_changed(path, content, check_only):
    existing = None
    if os.path.exists(path):
        with open(path) as handle:
            existing = handle.read()
    if existing == content:
        return False
    if check_only:
        return True
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as handle:
        handle.write(content)
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    manifest = load_manifest()
    luau_changed = write_if_changed(LUAU_OUT, render_luau(manifest), arguments.check)
    licenses_changed = write_if_changed(LICENSES_OUT, render_licenses(manifest), arguments.check)
    surfaces_changed = write_if_changed(SURFACES_OUT, render_surfaces(manifest), arguments.check)

    if arguments.check:
        if luau_changed or licenses_changed or surfaces_changed:
            print("generated files are out of date, run scripts/sync_configs.py")
            return 1
        print("generated files up to date")
        return 0

    total = len(manifest)
    approved = sum(1 for entry in manifest.values() if entry.get("assetId"))
    print(f"synced {total} entries ({approved} with asset ids)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
