#!/usr/bin/env python3
"""Generate src/shared/config/AssetIds.luau, assets/LICENSES.md, the prop surface
templates (assets/props/surfaces.model.json) and the in-game credits
(src/shared/config/CreditsConfig.luau) from the manifest.

Manifest keys are slash separated (audio/footsteps/metal_01) and become nested
Luau tables (AssetIds.audio.footsteps.metal_01). Entries without an approved
assetId are emitted as 0 so consumers stay silent instead of erroring.

Usage:
    python3 scripts/sync_configs.py [--check]

--check exits non-zero if the generated files are out of date, for CI use.
"""

import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "assets", "manifest.json")
LUAU_OUT = os.path.join(ROOT, "src", "shared", "config", "AssetIds.luau")
LICENSES_OUT = os.path.join(ROOT, "assets", "LICENSES.md")
SURFACES_OUT = os.path.join(ROOT, "assets", "props", "surfaces.model.json")
CREDITS_OUT = os.path.join(ROOT, "src", "shared", "config", "CreditsConfig.luau")

# texture/props/<prop>_<suffix> -> SurfaceAppearance property
SURFACE_MAPS = (
    ("color", "ColorMap"),
    ("normal", "NormalMap"),
    ("roughness", "RoughnessMap"),
    ("metalness", "MetalnessMap"),
)

HEADER = "--!strict\n\n-- Generated by scripts/sync_configs.py from assets/manifest.json. Do not edit by hand.\n\n"


def load_manifest():
    with open(MANIFEST) as handle:
        return json.load(handle)


def build_tree(manifest):
    tree = {}
    for key, entry in sorted(manifest.items()):
        parts = key.split("/")
        node = tree
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        asset_id = entry.get("assetId") or 0
        if entry.get("status") == "rejected":
            asset_id = 0
        node[parts[-1]] = asset_id
    return tree


def render(node, indent):
    pad = "\t" * indent
    lines = []
    for name in sorted(node.keys()):
        value = node[name]
        if isinstance(value, dict):
            lines.append(f"{pad}{name} = {{")
            lines.extend(render(value, indent + 1))
            lines.append(f"{pad}}},")
        else:
            lines.append(f"{pad}{name} = {value},")
    return lines


def render_luau(manifest):
    tree = build_tree(manifest)
    body = "\n".join(render(tree, 1))
    return f"{HEADER}local AssetIds = {{\n{body}\n}}\n\nreturn table.freeze(AssetIds)\n"


def render_licenses(manifest):
    rows = ["# Asset licenses", "", "Generated by `scripts/sync_configs.py`. Do not edit by hand.", ""]
    rows.append(
        "Anything marked **CC-BY** obliges us to credit the named author in the shipped game, "
        "not only in this file. Those credits are shown in the settings panel's Credits section, "
        "generated into `src/shared/config/CreditsConfig.luau` by the same script. CC0 and "
        "public-domain entries carry no such obligation. Share-alike "
        "(CC BY-SA) licences are deliberately not used anywhere here, because they would "
        "extend a copyleft obligation over the game itself."
    )
    rows.append("")
    rows.append("| Asset | License | Source | Asset ID | Status |")
    rows.append("| --- | --- | --- | --- | --- |")
    for key, entry in sorted(manifest.items()):
        source = entry.get("source", "")
        source_cell = f"[link]({source})" if source.startswith("http") else source
        rows.append(
            f"| `{key}` | {entry.get('license', '')} | {source_cell} | "
            f"{entry.get('assetId') or 'none'} | {entry.get('status', '')} |"
        )
    rows.append("")
    rows.append("Generated audio and textures marked `Original work (project owner)` were synthesised for this project.")
    if any(entry.get("license", "").startswith("Roblox generative AI output") for entry in manifest.values()):
        rows.append("")
        rows.append(
            "Entries marked `Roblox generative AI output (project owner)` are Cube 3D meshes and albedo maps "
            "produced by Roblox's GenerationService inside this project's own place and uploaded under the "
            "project owner's account; Roblox grants the generating creator the rights to use that output."
        )
    rows.append("")
    return "\n".join(rows)


def usable_id(entry):
    if not entry or entry.get("status") == "rejected":
        return 0
    return int(entry.get("assetId") or 0)


def render_surfaces(manifest):
    """One SurfaceAppearance per uploaded prop (model/props/<name>), named after the prop.

    SurfaceAppearance maps cannot be written by a game script, so WorldMeshes clones
    these Rojo-mounted templates (ReplicatedStorage.PropSurfaces) onto the MeshParts it
    creates. A prop entry may set "alphaMode" (for example "Transparency" for cut-out
    road signs); the default is Overlay.
    """
    children = []
    names = sorted(key.split("/", 2)[2] for key in manifest if key.startswith("model/props/"))
    for name in names:
        properties = {}
        for suffix, prop in SURFACE_MAPS:
            asset_id = usable_id(manifest.get(f"texture/props/{name}_{suffix}"))
            if asset_id:
                properties[prop] = f"rbxassetid://{asset_id}"
        if "ColorMap" not in properties:
            continue
        alpha = manifest[f"model/props/{name}"].get("alphaMode")
        if alpha:
            properties["AlphaMode"] = alpha
        children.append({"className": "SurfaceAppearance", "name": name, "properties": properties})
    tree = {"className": "Folder", "children": children}
    return json.dumps(tree, indent=2) + "\n"


# In-game credits (docs/gameplay/credits.md). Every CC BY entry (any version) that is
# approved or reviewing is credited, grouped by kind; the title, author, licence and
# source URL are read from the entry's own "license" and "source" strings, never
# written by hand. An entry the parser cannot read fails the run, so a new CC BY asset
# without a readable credit cannot ship silently.

CREDIT_STATUSES = ("approved", "reviewing")
CREDIT_GROUPS = ("Models and textures", "Animations", "Audio")
CC_BY = re.compile(r"\bCC[- ]?BY\b(?![- ]?(?:SA|NC|ND)\b)", re.IGNORECASE)
CC_BY_VERSION = re.compile(r"\bCC[- ]?BY[- ]?(\d(?:\.\d)?)", re.IGNORECASE)
URL = re.compile(r"https?://[^\s,;)\"]+")
DERIVED_FROM = re.compile(r"\(([a-z]+(?:/[\w.-]+)+)\)")


class CreditError(Exception):
    pass


def is_cc_by(entry):
    licence = entry.get("license") or ""
    return bool(CC_BY.search(licence)) and "CC0" not in licence.upper()


def credit_kind(key):
    if key.startswith("audio/"):
        return "Audio"
    if key.startswith("animation/"):
        return "Animations"
    return "Models and textures"


def _urls(text):
    return [url.rstrip(".") for url in URL.findall(text or "") if "creativecommons.org" not in url]


def _title_from_url(url):
    """The page's title from its URL slug (OpenGameArt pages are named by it)."""
    path = url.split("://", 1)[-1].rstrip("/")
    slug = path.rsplit("/", 1)[-1]
    words = [word for word in slug.split("-") if word and not re.fullmatch(r"[0-9a-f]{20,}", word)]
    if not words:
        return None
    text = " ".join(words)
    return text[0].upper() + text[1:]


def _quoted_by(text):
    """'"Title" by Author (@handle), https://...' or '...; uses ...' up to the URL."""
    match = re.search(r'"([^"]+)"\s+by\s+(.+?)(?:,\s*https?://|$)', text or "")
    if not match:
        return None, None
    author = match.group(2).strip().rstrip(",")
    return match.group(1).strip(), author


def _plain_by(text):
    """'Title by Author, https://...' (the Sketchfab props)."""
    match = re.match(r"\s*(.+?)\s+by\s+(.+?),\s*https?://", text or "")
    if not match:
        return None, None
    return match.group(1).strip(), match.group(2).strip()


def _author_from_licence(licence):
    credit = re.search(r"credit\s+(.+?)\s+on\s+\w+", licence)
    if credit:
        return credit.group(1).strip()
    # "CC-BY 3.0 - congusbongus, derived from X by Y (freesound N)"
    dashed = re.search(r"CC[- ]?BY[- ]?\d(?:\.\d)?\s+-\s+(.+)$", licence, re.IGNORECASE)
    if dashed and "credit" not in dashed.group(1) and "attribution" not in dashed.group(1):
        return dashed.group(1).strip()
    # "CC BY 3.0 (Vincent Sevedge)"
    paren = re.search(r"CC[- ]?BY[- ]?\d(?:\.\d)?\s*\(([^)]+)\)", licence, re.IGNORECASE)
    if paren and "://" not in paren.group(1):
        return paren.group(1).strip()
    return None


def parse_credit(key, manifest, seen=None):
    entry = manifest[key]
    source = entry.get("source") or ""
    licence_text = entry.get("license") or ""
    version = CC_BY_VERSION.search(licence_text)
    if not version:
        raise CreditError(f"{key}: no CC BY version in the licence")
    licence = f"CC BY {version.group(1)}"

    # a mesh read back from a Model upload carries the Model's credit
    if source.startswith("MeshId inside"):
        parent = DERIVED_FROM.search(source)
        seen = seen or set()
        if parent and parent.group(1) in manifest and parent.group(1) not in seen:
            seen.add(key)
            inherited = parse_credit(parent.group(1), manifest, seen)
            return dict(inherited, licence=licence)
        raise CreditError(f"{key}: a read-back mesh whose Model entry is not in the manifest")

    # an attribution the licence spells out ("Title" by Author, URL) wins over the source
    title, author = _quoted_by(licence_text)
    urls = (_urls(licence_text) + _urls(source)) if title else (_urls(source) or _urls(licence_text))
    if not title:
        title, author = _quoted_by(source)
    if not title:
        title, author = _plain_by(source)
    if not author:
        author = _author_from_licence(licence_text)
    url = urls[0] if urls else None
    if not title and url:
        title = _title_from_url(url)
    missing = [name for name, value in (("title", title), ("author", author), ("source URL", url)) if not value]
    if missing:
        raise CreditError(f"{key}: no {', '.join(missing)} readable from the manifest strings")
    return {"title": title, "author": author, "licence": licence, "url": url}


def credit_keys(manifest):
    return sorted(
        key for key, entry in manifest.items()
        if is_cc_by(entry) and entry.get("status") in CREDIT_STATUSES
    )


def build_credits(manifest):
    groups = {name: {} for name in CREDIT_GROUPS}
    for key in credit_keys(manifest):
        credit = parse_credit(key, manifest)
        line = (credit["title"], credit["author"], credit["licence"], credit["url"])
        groups[credit_kind(key)].setdefault(line, []).append(key)
    return groups


def build_acknowledgements(manifest):
    """Thanks not required by the licences (Mixamo's licence and the Free Firearm Sound
    Library's CC0 ask for no credit): one line each, present only while assets from
    them are in the manifest, the URL taken from the manifest."""
    lines = []
    mixamo = [e for e in manifest.values() if (e.get("license") or "").startswith("Mixamo") and e.get("status") in CREDIT_STATUSES]
    if mixamo:
        url = next((u for e in mixamo for u in _urls(e.get("license"))), "")
        lines.append({
            "title": "Character, arms and animations",
            "author": "Mixamo (Adobe)",
            "licence": "Mixamo licence, no attribution required",
            "url": url,
            "count": len(mixamo),
        })
    library = [e for e in manifest.values() if "Free Firearm Sound Library" in (e.get("source") or "") and e.get("status") in CREDIT_STATUSES]
    if library:
        url = next((u for e in library for u in _urls(e.get("source")) if "github.com" in u), "")
        lines.append({
            "title": "The Free Firearm Sound Library",
            "author": "Ben Jaszczak (GitHub mirror by buddingmonkey)",
            "licence": "CC0, no attribution required",
            "url": url,
            "count": len(library),
        })
    return lines


def _lua_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def render_credits(manifest):
    groups = build_credits(manifest)
    out = [
        "--!strict",
        "",
        "-- Generated by scripts/sync_configs.py from assets/manifest.json. Do not edit by hand.",
        "-- The in-game credits (docs/gameplay/credits.md): every CC BY asset, approved or",
        "-- reviewing, grouped by kind, one line per credited work with the manifest keys it",
        "-- covers; then the acknowledgements no licence requires.",
        "",
        "export type Credit = {",
        "\ttitle: string,",
        "\tauthor: string,",
        "\tlicence: string,",
        "\turl: string,",
        "\tassets: { string },",
        "}",
        "",
        "export type Group = {",
        "\tname: string,",
        "\tcredits: { Credit },",
        "}",
        "",
        "export type Acknowledgement = {",
        "\ttitle: string,",
        "\tauthor: string,",
        "\tlicence: string,",
        "\turl: string,",
        "\tcount: number,",
        "}",
        "",
        "local CreditsConfig = {}",
        "",
        "CreditsConfig.groups = {",
    ]
    for name in CREDIT_GROUPS:
        out.append("\t{")
        out.append(f"\t\tname = {_lua_string(name)},")
        out.append("\t\tcredits = {")
        for line in sorted(groups[name], key=lambda item: (item[0].lower(), item[1].lower())):
            title, author, licence, url = line
            out.append("\t\t\t{")
            out.append(f"\t\t\t\ttitle = {_lua_string(title)},")
            out.append(f"\t\t\t\tauthor = {_lua_string(author)},")
            out.append(f"\t\t\t\tlicence = {_lua_string(licence)},")
            out.append(f"\t\t\t\turl = {_lua_string(url)},")
            out.append("\t\t\t\tassets = {")
            for key in sorted(groups[name][line]):
                out.append(f"\t\t\t\t\t{_lua_string(key)},")
            out.append("\t\t\t\t},")
            out.append("\t\t\t},")
        out.append("\t\t},")
        out.append("\t},")
    out.append("} :: { Group }")
    out.append("")
    out.append("CreditsConfig.acknowledgements = {")
    for ack in build_acknowledgements(manifest):
        out.append("\t{")
        for field in ("title", "author", "licence", "url"):
            out.append(f"\t\t{field} = {_lua_string(ack[field])},")
        out.append(f"\t\tcount = {ack['count']},")
        out.append("\t},")
    out.append("} :: { Acknowledgement }")
    out.append("")
    out.append("-- shown above the list: the licences ask that changes be indicated")
    out.append('CreditsConfig.NOTE = "Assets adapted for the game: scaled, decimated, re-pivoted, retargeted, trimmed or filtered."')
    out.append("")
    out.append("return CreditsConfig")
    out.append("")
    return "\n".join(out)


def write_if_changed(path, content, check_only):
    existing = None
    if os.path.exists(path):
        with open(path) as handle:
            existing = handle.read()
    if existing == content:
        return False
    if check_only:
        return True
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as handle:
        handle.write(content)
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    manifest = load_manifest()
    luau_changed = write_if_changed(LUAU_OUT, render_luau(manifest), arguments.check)
    licenses_changed = write_if_changed(LICENSES_OUT, render_licenses(manifest), arguments.check)
    surfaces_changed = write_if_changed(SURFACES_OUT, render_surfaces(manifest), arguments.check)
    try:
        credits = render_credits(manifest)
    except CreditError as error:
        print(f"credits: {error}")
        return 1
    credits_changed = write_if_changed(CREDITS_OUT, credits, arguments.check)

    if arguments.check:
        if luau_changed or licenses_changed or surfaces_changed or credits_changed:
            print("generated files are out of date, run scripts/sync_configs.py")
            return 1
        print("generated files up to date")
        return 0

    total = len(manifest)
    approved = sum(1 for entry in manifest.values() if entry.get("assetId"))
    print(f"synced {total} entries ({approved} with asset ids)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
