#!/usr/bin/env python3
"""Generate src/shared/config/AssetIds.luau and assets/LICENSES.md from the manifest.

Manifest keys are slash separated (audio/footsteps/metal_01) and become nested
Luau tables (AssetIds.audio.footsteps.metal_01). Entries without an approved
assetId are emitted as 0 so consumers stay silent instead of erroring.

Usage:
    python3 scripts/sync_configs.py [--check]

--check exits non-zero if the generated files are out of date, for CI use.
"""

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "assets", "manifest.json")
LUAU_OUT = os.path.join(ROOT, "src", "shared", "config", "AssetIds.luau")
LICENSES_OUT = os.path.join(ROOT, "assets", "LICENSES.md")

HEADER = "--!strict\n\n-- Generated by scripts/sync_configs.py from assets/manifest.json. Do not edit by hand.\n\n"


def load_manifest():
    with open(MANIFEST) as handle:
        return json.load(handle)


def build_tree(manifest):
    tree = {}
    for key, entry in sorted(manifest.items()):
        parts = key.split("/")
        node = tree
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        asset_id = entry.get("assetId") or 0
        if entry.get("status") == "rejected":
            asset_id = 0
        node[parts[-1]] = asset_id
    return tree


def render(node, indent):
    pad = "\t" * indent
    lines = []
    for name in sorted(node.keys()):
        value = node[name]
        if isinstance(value, dict):
            lines.append(f"{pad}{name} = {{")
            lines.extend(render(value, indent + 1))
            lines.append(f"{pad}}},")
        else:
            lines.append(f"{pad}{name} = {value},")
    return lines


def render_luau(manifest):
    tree = build_tree(manifest)
    body = "\n".join(render(tree, 1))
    return f"{HEADER}local AssetIds = {{\n{body}\n}}\n\nreturn table.freeze(AssetIds)\n"


def render_licenses(manifest):
    rows = ["# Asset licenses", "", "Generated by `scripts/sync_configs.py`. Do not edit by hand.", ""]
    rows.append("| Asset | License | Source | Asset ID | Status |")
    rows.append("| --- | --- | --- | --- | --- |")
    for key, entry in sorted(manifest.items()):
        source = entry.get("source", "")
        source_cell = f"[link]({source})" if source.startswith("http") else source
        rows.append(
            f"| `{key}` | {entry.get('license', '')} | {source_cell} | "
            f"{entry.get('assetId') or '—'} | {entry.get('status', '')} |"
        )
    rows.append("")
    rows.append("Generated audio and textures marked `Original work (project owner)` were synthesised for this project.")
    rows.append("")
    return "\n".join(rows)


def write_if_changed(path, content, check_only):
    existing = None
    if os.path.exists(path):
        with open(path) as handle:
            existing = handle.read()
    if existing == content:
        return False
    if check_only:
        return True
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as handle:
        handle.write(content)
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    manifest = load_manifest()
    luau_changed = write_if_changed(LUAU_OUT, render_luau(manifest), arguments.check)
    licenses_changed = write_if_changed(LICENSES_OUT, render_licenses(manifest), arguments.check)

    if arguments.check:
        if luau_changed or licenses_changed:
            print("generated files are out of date, run scripts/sync_configs.py")
            return 1
        print("generated files up to date")
        return 0

    total = len(manifest)
    approved = sum(1 for entry in manifest.values() if entry.get("assetId"))
    print(f"synced {total} entries ({approved} with asset ids)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
